export const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

export const SOURCE_CONFIGS = [
  {
    key: "fpsc",
    name: "FPSC",
    url: "https://www.fpsc.gov.pk/jobs/gr/current-jobs",
    category: "Latest Jobs",
    organization: "Federal Public Service Commission",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "ppsc",
    name: "PPSC",
    url: "https://www.ppsc.gop.pk/(S(0))/",
    category: "Latest Jobs",
    organization: "Punjab Public Service Commission",
    province: "Punjab",
    city: "Lahore",
  },
  {
    key: "spsc",
    name: "SPSC",
    url: "https://www.spsc.gov.pk/",
    category: "Latest Jobs",
    organization: "Sindh Public Service Commission",
    province: "Sindh",
    city: "Hyderabad",
  },
  {
    key: "bpsc",
    name: "BPSC",
    url: "https://bpsc.gob.pk/",
    category: "Latest Jobs",
    organization: "Balochistan Public Service Commission",
    province: "Balochistan",
    city: "Quetta",
  },
  {
    key: "kppsc",
    name: "KPPSC",
    url: "https://www.kppsc.gov.pk/",
    category: "Latest Jobs",
    organization: "Khyber Pakhtunkhwa Public Service Commission",
    province: "Khyber Pakhtunkhwa",
    city: "Peshawar",
  },
  {
    key: "pak-army",
    name: "Join Pakistan Army",
    url: "https://www.joinpakarmy.gov.pk/",
    category: "Latest Jobs",
    organization: "Pakistan Army",
    province: "Islamabad",
    city: "Rawalpindi",
  },
  {
    key: "pak-navy",
    name: "Join Pakistan Navy",
    url: "https://joinpaknavy.gov.pk/",
    category: "Latest Jobs",
    organization: "Pakistan Navy",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "pak-paf",
    name: "Join Pakistan Air Force",
    url: "https://joinpaf.gov.pk/",
    category: "Latest Jobs",
    organization: "Pakistan Air Force",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "punjab-police",
    name: "Punjab Police Jobs",
    url: "https://punjabpolice.gov.pk/police-jobs",
    category: "Latest Jobs",
    organization: "Punjab Police",
    province: "Punjab",
    city: "Lahore",
  },
  {
    key: "sindh-police",
    name: "Sindh Police Jobs",
    url: "https://sindhpolice.gov.pk/jobs",
    category: "Latest Jobs",
    organization: "Sindh Police",
    province: "Sindh",
    city: "Karachi",
  },
  {
    key: "islamabad-police",
    name: "Islamabad Police Jobs",
    url: "https://islamabadpolice.gov.pk/careers.php",
    category: "Latest Jobs",
    organization: "Islamabad Capital Territory Police",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "pmo",
    name: "Prime Minister Office",
    url: "https://pmo.gov.pk/news",
    category: "New Schemes",
    organization: "Prime Minister Office",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "pmyp",
    name: "Prime Minister Youth Programme",
    url: "https://www.pmyp.gov.pk/",
    category: "New Schemes",
    organization: "Prime Minister Youth Programme",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "hec-scholarships",
    name: "HEC Scholarships",
    url: "https://www.hec.gov.pk/english/scholarshipsgrants/Pages/default.aspx",
    category: "New Schemes",
    organization: "Higher Education Commission",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "dlims",
    name: "Driving License",
    url: "https://dlims.punjab.gov.pk/",
    category: "New Schemes",
    organization: "Driving License Information Management System",
    province: "Punjab",
    city: "Lahore",
  },
  {
    key: "punjab-land-records",
    name: "Land Records",
    url: "https://www.punjab-zameen.gov.pk/",
    category: "New Schemes",
    organization: "Punjab Land Records Authority",
    province: "Punjab",
    city: "Lahore",
  },
  {
    key: "fbr-tax",
    name: "Tax Portal",
    url: "https://e.fbr.gov.pk/",
    category: "New Schemes",
    organization: "Federal Board of Revenue",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "pm-health-card",
    name: "Health Card",
    url: "https://www.pmhealthprogram.gov.pk/",
    category: "New Schemes",
    organization: "Sehat Sahulat Program",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "navttc-training",
    name: "Training",
    url: "https://www.navttc.gov.pk/",
    category: "New Schemes",
    organization: "NAVTTC",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "kissan-card",
    name: "Kissan Card",
    url: "https://agripunjab.gov.pk/kissan-card",
    category: "New Schemes",
    organization: "Agriculture Department Punjab",
    province: "Punjab",
    city: "Lahore",
  },
  {
    key: "punjab-energy",
    name: "Solar Program",
    url: "https://energy.punjab.gov.pk/",
    category: "New Schemes",
    organization: "Energy Department Punjab",
    province: "Punjab",
    city: "Lahore",
  },
  {
    key: "amis-market-rates",
    name: "Market Rates",
    url: "https://www.amis.pk/",
    category: "New Schemes",
    organization: "Agriculture Marketing Information Service",
    province: "Punjab",
    city: "Lahore",
  },
  {
    key: "bisp",
    name: "BISP",
    url: "https://www.bisp.gov.pk/",
    category: "New Schemes",
    organization: "Benazir Income Support Programme",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "punjab-news",
    name: "Punjab Government News",
    url: "https://punjab.gov.pk/news",
    category: "New Schemes",
    organization: "Government of Punjab",
    province: "Punjab",
    city: "Lahore",
  },
  {
    key: "sindh-news",
    name: "Sindh Government News",
    url: "https://sindh.gov.pk/",
    category: "New Schemes",
    organization: "Government of Sindh",
    province: "Sindh",
    city: "Karachi",
  },
];
