export const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

export const SOURCE_CONFIGS = [
  {
    key: "fpsc",
    name: "FPSC",
    url: "https://www.fpsc.gov.pk/jobs/gr/current-jobs",
    category: "Latest Jobs",
    organization: "Federal Public Service Commission",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "ppsc",
    name: "PPSC",
    url: "https://www.ppsc.gop.pk/(S(0))/",
    category: "Latest Jobs",
    organization: "Punjab Public Service Commission",
    province: "Punjab",
    city: "Lahore",
  },
  {
    key: "spsc",
    name: "SPSC",
    url: "https://www.spsc.gov.pk/",
    category: "Latest Jobs",
    organization: "Sindh Public Service Commission",
    province: "Sindh",
    city: "Hyderabad",
  },
  {
    key: "bpsc",
    name: "BPSC",
    url: "https://bpsc.gob.pk/",
    category: "Latest Jobs",
    organization: "Balochistan Public Service Commission",
    province: "Balochistan",
    city: "Quetta",
  },
  {
    key: "kppsc",
    name: "KPPSC",
    url: "https://www.kppsc.gov.pk/",
    category: "Latest Jobs",
    organization: "Khyber Pakhtunkhwa Public Service Commission",
    province: "Khyber Pakhtunkhwa",
    city: "Peshawar",
  },
  {
    key: "pak-army",
    name: "Join Pakistan Army",
    url: "https://www.joinpakarmy.gov.pk/",
    category: "Latest Jobs",
    organization: "Pakistan Army",
    province: "Islamabad",
    city: "Rawalpindi",
  },
  {
    key: "pak-navy",
    name: "Join Pakistan Navy",
    url: "https://joinpaknavy.gov.pk/",
    category: "Latest Jobs",
    organization: "Pakistan Navy",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "pak-paf",
    name: "Join Pakistan Air Force",
    url: "https://joinpaf.gov.pk/",
    category: "Latest Jobs",
    organization: "Pakistan Air Force",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "pmo",
    name: "Prime Minister Office",
    url: "https://pmo.gov.pk/news",
    category: "New Schemes",
    organization: "Prime Minister Office",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "bisp",
    name: "BISP",
    url: "https://www.bisp.gov.pk/",
    category: "New Schemes",
    organization: "Benazir Income Support Programme",
    province: "Islamabad",
    city: "Islamabad",
  },
  {
    key: "punjab-news",
    name: "Punjab Government News",
    url: "https://punjab.gov.pk/news",
    category: "New Schemes",
    organization: "Government of Punjab",
    province: "Punjab",
    city: "Lahore",
  },
  {
    key: "sindh-news",
    name: "Sindh Government News",
    url: "https://sindh.gov.pk/",
    category: "New Schemes",
    organization: "Government of Sindh",
    province: "Sindh",
    city: "Karachi",
  },
];
